### ISSUE TITLE
Expo example has error. 

### ISSUE THREAD

**Issue by markdevjapan** [mxmzb/react-native-gesture-detector#1]
In your repo, you have this structure:

`/src/Screen/Triangle.js`

But in the [snack expo ](https://snack.expo.io/@mxmzb/react-native-gesture-detector)example, it is: 

`/src/Screen/TriangleScreen.js`

Which means the import is failing:

`import TriangleScreen from "./src/Screen/Triangle";`

and is giving this error:

> Unable to resolve module 'module://src/Screen/Triangle.js'

**Comment by mxmzb** [comment]
Nice catch, thank you!
